### ISSUE TITLE
Fails to build with ffmpeg >= 5.0

### ISSUE THREAD

**Issue by david-geiger** [xtingray/tupitube.desk#87]
Hi,

tupitube doesn't build with ffmpeg >= 5.0 on Mageia Cauldron, there are some build error like:

`main.cpp:46:45: error: invalid conversion from 'const AVOutputFormat*' to 'AVOutputFormat*' [-fpermissive]
   46 |     AVOutputFormat *format = av_guess_format("ffh264", NULL, NULL);
      |                              ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const AVOutputFormat*
main.cpp:56:42: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
   56 |     AVCodec *codec = avcodec_find_encoder(stream->codecpar->codec_id);
      |                      ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          const AVCodec*
make: *** [Makefile:379: main.o] Error 1
tupaudiomixer.cpp: In member function 'int TupAudioMixer::openInputFile(const char*)':
tupaudiomixer.cpp:131:45: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  131 |     if (!(input_codec = avcodec_find_decoder(audioCodecID))) {
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |                                             |
      |                                             const AVCodec*
tupaudiomixer.cpp: In member function 'void TupAudioMixer::setCodecContextParameters()':
tupaudiomixer.cpp:197:40: warning: 'AVCodecContext::channel_layout' is deprecated [-Wdeprecated-declarations]
  197 |         if (!inputCodecContextList[i]->channel_layout)
      | 
tupaudiomixer.cpp: In member function 'int TupAudioMixer::openOutputFile(const char*, AVCodecContext*)':
tupaudiomixer.cpp:527:57: error: invalid conversion from 'const AVOutputFormat*' to 'AVOutputFormat*' [-fpermissive]
  527 |     AVOutputFormat *outputFormat = outputFormatContext->oformat;
      |                                    ~~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                                         |
      |                                                         const AVOutputFormat*
tupaudiomixer.cpp:531:45: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  531 |     if (!(outputCodec = avcodec_find_encoder(audioCodecID))) {
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |                                             |
      |                                             const AVCodec*
tupaudiomixer.cpp: In member function 'int TupAudioMixer::decodeAudioFrame(AVFrame*, AVFormatContext*, AVCodecContext*, int*, int*)':
tupaudiomixer.cpp:683:18: error: 'avcodec_decode_audio4' was not declared in this scope; did you mean 'avcodec_decode_subtitle2'?
  683 |     if ((error = avcodec_decode_audio4(inputCodecContext, frame,
      |                  ^~~~~~~~~~~~~~~~~~~~~
      |                  avcodec_decode_subtitle2
make[4]: *** [Makefile:458: .obj/tupaudiomixer.o] Error 1`

Regards,
David

**Comment by xtingray** [comment]
Hi,
I just want you to know that the TupiTube source code requires a lot of refactoring and updating, including the Qt libraries and other dependencies like the FFmpeg latest version. This process will take several months, so for now, a workaround is using FFmpeg version 4.4.

**Comment by david-geiger** [comment]
Impossible to use a very old ffmpeg version in a stable distribution, we do not have it and we do not want to maintain some ffmpeg package version.

**Comment by xtingray** [comment]
I got it. It will take a while to upgrade the code depending on the FFmpeg package from my side, but I expect to notify you as soon as possible. Sorry for the inconvenience.
